# the checks to perform:

# format is:
# check = filename : variable1<type>(precision) variable2<type>(precision) ...
#
# <type> is optional and can be 'n' (numeric data, default) or 's' (string data)
# (default precision is 1e-6)
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:

# specify the input file to run
inputfile = Si_NWFET.tib

# specify the output directory
outputdir = output_IV

check = driftdiffusion_Vg_-0.5_msh.vtu : Ec eQFermi
check = driftdiffusion_Vg_2_msh.vtu : Ec eQFermi
check = sweep_drain_driftdiffusion_Vg_1.dat : source.current
check = transchar_driftdiffusion.dat : source.current
