# the checks to perform:

# format is:
# check = filename : variable1(precision) variable2(precision) ...
#
# (default precision is 1e-6)
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:

inputfile = tut_02.tib
outputdir = output

check = tt_msh.dat : LatticeTemp 
check = sweep_tt.dat : MaxTemp 
