# the checks to perform:

# format is:
# check = filename : variable1(precision) variable2(precision) ...
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:


inputfile = bulk.tib
outputdir = output

check = tb_dispersion.dat : state_number_0	state_number_1	state_number_2	state_number_3	state_number_4	state_number_5	state_number_6	state_number_7	state_number_8	state_number_9 state_number_10

