Module poisson
{
  # install here (default is in the tibercad installation's
  # module directory
  installpath = .

  # the sources for the main module library (the first one provides
  # the creatable object)
  sources = (Poisson.cpp, PoissonModel.cpp, PoissonBoundaryModel.cpp)

  # to provide the creatable class explicitly
  #creatable = Poisson

  # one might add some extra code for the creation routine
  #creator_code = 

  charge_density { sources = models/ChargeDensity.cpp }

  # 'contact' is the keyword used to build the library.
  # (It does not appear in the input file)
  contact dirichlet { sources = models/PoissonDirichlet.cpp }
  contact neumann   { sources = models/PoissonNeumann.cpp }

}

