# the checks to perform:

# format is:
# check = filename : variable1(precision) variable2(precision) ...
#
# (default precision is 1e-6)
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:

inputfile = quantum_dot.tib
outputdir = output

check = dd_msh.vtu : Ec(1e-3) Ev(1e-3)
check = strain_msh.vtu : Strain Stress(1e-2)
check = quantum_el.dat : EigenEnergy
check = quantum_hl.dat : EigenEnergy
check = quantum_el_msh.vtu : eDensity(1e-2)
check = quantum_hl_msh.vtu : hDensity(1e-2)
