# the checks to perform:

# format is:
# check = filename : variable1(precision) variable2(precision) ...
#
# (default precision is 1e-6)
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:

inputfile = InGaAs_1D.tib
outputdir = output

check = strain_msh.dat : Strain_11
check = driftdiffusion_msh.dat : Ec Ev
check = quantum_electrons_msh.dat : ProbabilityDensity_0 ProbabilityDensity_1
check = quantum_electrons.dat : EigenEnergy
check = quantum_holes_msh.dat : ProbabilityDensity_11 ProbabilityDensity_9
check = quantum_holes.dat : EigenEnergy
