# the checks to perform:

# format is:
# check = filename : variable1(precision) variable2(precision) ...
#
# If you omit any vaiables, then it will just check
# if the file has been generated.
#
# You can define more than one check
#
# examples:

commandline = ./sweep_angles.sh sweep

outputdir = ./

check = sweep/P_vs_angle.dat : P exx eyy ezz exz

check = output_10-1-1/tb.xyz  : x y z species<s>
check = output_10-1-1/efa.dat : EigenEnergy
check = output_10-1-1/tb.dat  : EigenEnergy
check = output_10-1-1/dd_msh.dat  : Ec Ev

check = output_10-1-3/tb.xyz  : x y z species<s>
check = output_10-1-3/efa.dat : EigenEnergy
check = output_10-1-3/tb.dat  : EigenEnergy
check = output_10-1-3/dd_msh.dat  : Ec Ev

check = output_11-22/tb.xyz  : x y z species<s>
check = output_11-22/efa.dat : EigenEnergy
check = output_11-22/tb.dat  : EigenEnergy
check = output_11-22/dd_msh.dat  : Ec Ev
